### ISSUE TITLE
Add an icon

### ISSUE THREAD

**Issue by lrettig** [stacksgov/pm#10]
It would be nice to have an easily-identifiable icon we can use here on GitHub, and elsewhere (e.g., Youtube), for the stacksgov brand/initiative.

**Comment by whoabuddy** [comment]
I agree, but I am curious how this plays into overall branding? Maybe we should look broader at a style guide? Do we eventually want a logo? Are we using Blockstack colors or something different? (Ideally, give the impression of separate but related).

For the short term [a jdenticon](https://jdenticon.com/icon-designer.html) might be a fun option - we could design a set to cover certain resources with a theme, that way if we have to brand more than one thing the icons will be consistent. (Stacksgov, Youtube, etc)

For example, the set below uses something close to Blockstack's #211F6D primary color (using [colorhexa](https://www.colorhexa.com/211f6d) to estimate HSL values):

![2020-03-13 08 19 22 jdenticon com dba4f1b59f63](https://user-images.githubusercontent.com/9038904/76634400-6c081e00-6503-11ea-971b-1f05e9c9df25.png)

**Comment by whoabuddy** [comment]
Another idea: this logo came up as part of trying out a jdenticon using the github org URL (https://github.com/stacksgov)

![20200317 jdenticon-github-stacksgov-org](https://user-images.githubusercontent.com/9038904/76906515-537c6880-6861-11ea-98d9-bce84aaf7822.png)

I like the smaller box inside with the triangles, since it's similar to the Blockstack block, but different enough it can be recognized on its own. For the color I went with `#1F6D21` because it's a triadic color to Blockstack blue `#211f6d`.

![20200317 green square](https://user-images.githubusercontent.com/9038904/76906806-fc2ac800-6861-11ea-9169-71c82fb74f06.png)

**Comment by lrettig** [comment]
I really like the smaller green box - this is great! Shall we throw this up for now as a placeholder and see how it feels?

**Comment by whoabuddy** [comment]
I say we go for it - we've circulated this a few places with no feedback, and it feels better to have the green box than the default github logo!

**Comment by whoabuddy** [comment]
After discussing this in the [last community call on 2020/03/25](https://github.com/stacksgov/resources/blob/master/calls/notes/2020-03-25-Meeting-0005.md) we have reached consensus and will start to implement the green icon across all outlets.

The image files will be uploaded to the resources repo, link TBA.

The checklist below represents where we want to update the image before closing this issue.

- [x] Github Organization
- [ ] Google / Youtube Account
- [ ] Youtube Watermark

Feel free to comment on any other locations we should update it!

**Comment by whoabuddy** [comment]
All outlets have been updated and added 150x150 png file to resources repo per [#24](https://github.com/stacksgov/resources/pull/24)
