### ISSUE TITLE
Update stacksgov brand assets

### ISSUE THREAD

**Issue by jennymith** [stacksgov/pm#115]
Maybe not necessary but curious to hear what others think.

**Comment by whoabuddy** [comment]
I think it's a good idea and bet we could come up with something based on the new branding!

https://stx.design

**Comment by whoabuddy** [comment]
Update: I drafted up two designs and asked the question if we should use "Stacks Governance" or "Stacks Community Governance" as the name in the survey below.

https://survey.absorbingchaos.com/survey/189ZWJqLxL1ZhFPMfLKfUoHfDePdLex7cL/332c90c5-454e-4afc-90a4-578ed9ad4a8b

Still looking for additional feedback, anyone is welcome to take the survey!

Results so far across 4 respondents:

- 3 to 1 for "Stacks Community Governance" over "Stacks Governance"
- The Metaverse Building is more popular than the Scales (avg 6.25/10 to 3.75/10)
- The "if we had to choose today" answers were unanimous on the square logo of the building with a STX symbol

Preview:

![stacksgov_logo_building_square_withlogo_white](https://user-images.githubusercontent.com/9038904/111649817-f55eca00-87c1-11eb-8dea-bc0d7aaa99fb.png)

**Comment by whoabuddy** [comment]
**Update:** rebranding survey up to 12 responses!
  - 8 for "community" in the name, 4 not
  - building preferred over scales
  - common feedback: the building may be too western-centric
  - some new ideas have been submitted - a new survey will be created and circulated (preview below)

![napkin-drawing](https://user-images.githubusercontent.com/9038904/113328832-a93b7b80-92d1-11eb-906d-2a381c13e9ba.png)

**Comment by 314159265359879** [comment]
I really like 2 and 5 with the stacks logo inside a _round table_ or _puzzle pieces_. 
9 a more subtle logo can still be seen, I think it will be favorite among the metaversers because its logo is included too ;-)

**Comment by tony-rengel** [comment]
2 was the most productive design path.  The Designer felt attempts at the puzzle pieces were too busy.  Here are the motifs he's mocked up - all elements are up for (re)combination/discussion.  All thoughts appreciated, these designs are free to iterate on as well. 

All credit to the Designer, Travis Milam 

![stacksConcepts](https://user-images.githubusercontent.com/79322531/114217806-80446780-991d-11eb-8a49-1f09e47c5204.png)

**Comment by 314159265359879** [comment]
I like 2 best, a compact form that tells a story; seats at a round table to deliberate about a user owned internet on stacks. The round table can still be perceived, and also triangular torso's with heads on them, creating interesting ways to animate the logo.

**Comment by joberding** [comment]
I like 1 and 5

**Comment by HaroldDavis3** [comment]
> I like 1 and 5

Me Too-- and the colors --maybe combo of 5 with colors of 1 :)

**Comment by whoabuddy** [comment]
New survey based on the 5 options listed here, would love everyone's feedback, kept it short and sweet this time!

https://shrl.ink/SDii

**Comment by jennymith** [comment]
Votes due before the next gov meeting!

**Comment by eugeniadigon** [comment]
Hello everyone 👋  I'm Eugenia, I'm the designer who's been helping recently with Stacks official brand. There are some interesting propositions here! If I can chime in, I have a couple of suggestions to make:

- Ideally, the "metaverse" gradient, shouldn't be used inside of shapes. If we do that, it'll make really hard to work with the logo in the future, like placing it in different places over different backgrounds. It's always preferred to use black and white color schemes, so we're sure it'll always work no matter where we place it, and we can save ourselves some headaches. Overall, gradients are meant to be supporting elements of the brand, meant to be used on other parts of visual compositions, and not inside logos.

- Regarding the Nexus symbol, it's always better to give it some air and not "trap" it inside shapes, so it's always distinguishable at first glance

- In general, it's much better if logos are simple shapes and not complex geometric compositions with different types of shapes and different sizes of shapes. This is because if we scale down the logo, we risk it not being legible and making it very incomprehensible in small sizes. As a rule of thumb, it's recommended to test logos in small sizes, beginning at 24px, 32px, 48px height... If you can't easily visualize the logo at those sizes, it's probably too complex!

- As a plus, having simpler logos also avoids undesirable references to particular cultures or geographic places. 


If the subject is still open for proposals, I can suggest this version which is more simple and unmistakably Stacks:
![image](https://user-images.githubusercontent.com/78865845/116669663-2294bf80-a99f-11eb-9daa-1a8f8683b14b.png)



I also tried one of the previous concepts which I thought could work well:
![image](https://user-images.githubusercontent.com/78865845/116669689-2aecfa80-a99f-11eb-806d-b08db5181fe8.png)


[Stacks Governance Logo.zip](https://github.com/stacksgov/pm/files/6403957/Stacks.Governance.Logo.zip)

**Comment by BaiHuLaoShi** [comment]
The experiential context is HUGE, thank you for your time and detail 🙏

I like the second logo you drew up from the napkin drawings, it captures a "STX all over the globe" feeling that feels on-vibe

**Comment by whoabuddy** [comment]
Update for all - I have not had as much time to dedicate to this as I'd like, and I apologize for the delay.

Thank you to everyone who's responded to the 2nd survey, I closed it this morning and here's a rough breakdown of the results from 38 respondents:

Out of the 5 options presented from [this earlier comment](https://github.com/stacksgov/pm/issues/115#issuecomment-816843369):

- Option 1: 16 votes
- Option 2: 1 votes
- Option 3: 4 votes
- Option 4: 5 votes
- Option 5: 12 votes

Option 1 and Option 5 were the most-liked, with some general feedback around designs, possible improvements, and a lot of support. ❤️ 

I'd like to gather everyone's opinions on the new designs in the comment above and feel that another survey may be the best way to do so. Will work to keep it short and sweet, and hopefully have it prepared to share in the next governance meeting.

**Comment by joberding** [comment]
I give a plus 1 for @eugeniadigon's  option 2
Thank you to all for your work!!!

**Comment by 314159265359879** [comment]
> 
> 
> I give a plus 1 for @eugeniadigon's option 2
> Thank you to all for your work!!!

One more +1 for option 2, I really like the implied globe.

**Comment by whoabuddy** [comment]
Thank you everyone for the updates, I'd like to put this together as an emoji vote here on GitHub to get this closed out once and for all, rather than going through creating a survey and sharing it out.

So, **if you'd like to vote on the Stacksgov logo**, please emoji this comment with either:

:rocket: for Option 1:

![116669663-2294bf80-a99f-11eb-9daa-1a8f8683b14b](https://user-images.githubusercontent.com/9038904/131902549-afc1e394-1bb5-4261-8795-0239506595bf.png)

:tada: for Option 2:

![116669689-2aecfa80-a99f-11eb-806d-b08db5181fe8](https://user-images.githubusercontent.com/9038904/131902569-5758403b-d2c5-4fd1-8a6a-5611dd52ddff.png)

I will tally up the votes and discuss it in the next governance meeting two weeks from now, and from there we'll get this one closed out!

*and thank you to @eugeniadigon for putting these together!*

**Comment by whoabuddy** [comment]
Quick update:

- added the brand resources to the resources repo, deleted old logos
- added the logo to the Docsify config for both sites
(#115 / stacksgov/resources#57)
- added the logo to the GitHub org profile as an avatar
- added the logo on all repositories except the grants program, advocates program

I believe that covers all the spots we'd want it. The 1280x640 size for each GitHub repository would leave enough room to add text at the bottom of each logo, but I wanted to keep this first iteration simple so we can get it done.

If anyone runs into any issues, finds something I missed, or has any comments, please voice them!

**Comment by whoabuddy** [comment]
Closing out after discussion in #167 that the goals are complete!
