### ISSUE TITLE
Source Code Licensing 

### ISSUE THREAD

**Issue by HaroldDavis3** [stacksgov/pm#171]
## Discussion From Friedger on Discord

**F:** Was there any discussions/decisions that Stacks foundation donates a lot of source code to Hiro?

**H:** No discussions of this in todays gov meeting, sorry we missed you mane; has there been a lil discussion on this already? 
Sounds interesting for sure so Ty kindly for dropping it in here, feel free to drop an issue here: https://github.com/stacksgov/pm/issues if you'd like to get a discussion started for next time we meet. I can also just meet w/you asap too, know the timezone may not be the easiest to catch us. This way even if you cant catch us we still get the sentiment into our documentation and recorded meetings 🙏🏾

**F:** It looks like Hiro PBC is the legal successor of Blockstack PBC, so it is just fair if the code is hosted there.
Should the foundation manage a reference implementation of the blockchain node and of the auth protocol and tx signing protocol?

**Comment by joberding** [comment]
Following up on my comment in the Gov wg this morning. My recollection from statements made in interviews (and my memory could be wrong about this) was that Blockstack was no longer legally responsible for the Stacks ecosystem and Stacks. I’m unsure if Hiro actually stands in the shoes of Blockstack.  It seems that some responsibilities were transferred to the Foundation while others went to Hiro.  If so, what is Hiro responsible for as a result, if anything. And I am writing from a legal perspective. Others have more clarity on the technical issues.

**Comment by diwakergupta** [comment]
@HaroldDavis3 @joberding I just happen to notice this issue because of the Hiro mention. I'm not sure I follow the exact question or concern though. If there's a specific question (from Friedger or others) with regards to Hiro, please tag me and I'd be happy to answer.

Meanwhile, some basics:

- Hiro PBC does not "host" any source code. Hiro primarily uses the [hirosystems](https://github.com/hirosystems) Github org (for projects like Clarinet, API etc). Then there is the [stacks-network](https://github.com/stacks-network) (which has the stacks-blockchain repo), which Hiro is a contributor to, like many others. Both of these are technically "hosted" by Github.
- The reference implementation of Stacks blockchain found in the [stacks-blockchain](https://github.com/stacks-network/stacks-blockchain) repo is already under the Foundation / Community governance, via the SIP process described in SIP-000.
- Hiro does NOT participate in Stacks mining. Hiro does run many Stacks follower nodes, among other services.

**Comment by friedger** [comment]
@diwakergupta My questions are
* Does Hiro PBC own the copyright on stacks.js? If yes, since when? 
* How was the copyright transferred from Blockstack PBC?

**Comment by diwakergupta** [comment]
> @diwakergupta My questions are
> 
> * Does Hiro PBC own the copyright on stacks.js? If yes, since when?

stacks.js was and continues to be licensed under the MIT license. There's been no change to the license, at least none that I'm aware of. I'd also be careful in using "copyright" vs. "license" -- I'm not an expert on open-source legalese.

> * How was the copyright transferred from Blockstack PBC?

Hiro PBC was fka Blockstack PBC, so "transfer" in this context doesn't make sense (they're the same legal entity).

Can I request this issue be re-worded/re-written to add more context and specificity: right now someone coming across this issue on the interwebs would be left very confused as to what is actually being discussed.
