### ISSUE TITLE
Call for written contributions: Give some background on the governance working group.

### ISSUE THREAD

**Issue by blockstackers** [stacksgov/pm#27]
Consider the following when providing your answer:
- Describe the origins of this working group.
- Describe the backgrounds of the governance working group members.
- Why are group members interested in working on governance for Blockstack?
- What roles do Lane and Brittany play in relation to community members?

**All answers will contribute to a longer form blog detailing the work that this group has done on governance so far. (Pending review and approval from group members, of course.)**

**Comment by lrettig** [comment]
- Describe the origins of this working group.

It began as a call in February where Brittany introduced me to the community, and then I shared some high-level thoughts on governance, and answered questions. After that, Jenny helped us set up the working group (presumably modeled after existing working groups!). Juliet and Jason very quickly became involved and helped bootstrap the initiative, including PM work in GitHub, moderating the weekly calls, etc. It's loosely based on existing governance initiatives that I've been a part of, such as the Ethereum all core devs calls, but it's been modified to suit our needs and has already evolved quite a bit since the beginning :)

- Describe the backgrounds of the governance working group members.

I won't speak for anyone else, but I'm a software developer who has a background in entrepreneurship and a keen interest in governance, and more generally in people and in social systems, including topics such as political philosophy and law. In the blockchain ecosystem, I worked as a core developer for the Ethereum Foundation from 2017-2019, and was very active during this time in Ethereum governance. In addition to independent research and consulting on governance, I work on software development for a project called Spacemesh, and write on the side.

- Why are group members interested in working on governance for Blockstack?

My motivation is that I think the Blockstack ecosystem is uniquely positioned in the blockchain space to not only raise the bar considerably on governance - which I feel has been neglected in most blockchain projects to date - but, on the strength of good governance, to deliver a platform that really moves the needle for humanity in some important ways. To me, platform and governance are intertwined and interdependent and you cannot have one without the other. Very few projects that have reached the degree of maturity of the Blockstack ecosystem and platform are taking governance as seriously as we are!

- What roles do Lane and Brittany play in relation to community members?

I think I'll let others speak to this one first! :)

**Comment by joberding** [comment]
- Describe the backgrounds of the governance working group members.

While I can’t speak to each person’s background, I have observed that members are developers, app founders, entrepreneurs, evangelists, STX holders and active community members. 

As for myself, I have a background as a lawyer (litigation/IP) turned startup founder, CEO of Predictably Well. In the Blockstack community, I am app founder of [Dappity](https://dappity.app) and [Person8](https://app.person8.org/) and  an evangelist [San Francisco Community](https://www.meetup.com/Blockstack-SF/)

I’m passionate about social good projects, the intersection of  technology and health, solving health inequities, privacy and human rights. And yes, I am pretty passionate about the Blockstack mission :) Good governance is necessary to make sure the mission succeeds.

- What roles do Lane and Brittany play in relation to community members?
Both Lane and Brittany play significant roles in the current and future development of Blockstack governance. Lane is active in creating the proposals that outline the future of governance, while Brittany is overseeing the structure of the future foundation. Both are active on the governance working group. Both are stewards and fellow community members.
