### ISSUE TITLE
Call for written contributions: What's next for the governance working group and what does this work mean for the Blockstack ecosystem?

### ISSUE THREAD

**Issue by blockstackers** [stacksgov/pm#30]
Consider the following when providing your answer: 

- What comes after the governance proposal?
- How will it be enforced?
- Are there any stakeholder perspectives that we're missing?
- How can we improve on the work that we're currently doing?
- What can the broader Blockstack community do to ensure that we are "doing governance right"?
- What are we hoping to take from other crypto projects and what are we hoping to avoid?
- What is unique about the Blockstack ecosystem? 
- How do these unique qualities impact the way that we approach governance?
- Is our approach to governance different because of these unique qualities?

**All answers will contribute to a longer form blog detailing the work that this group has done on governance so far. (Pending review and approval from group members, of course.)**

**Comment by HaroldDavis3** [comment]
I have a WIP here. Will attempt to show what makes our research approach different thus far by addressing the important challenges @lrettig has put forward. Figure I can do my best with addressing these challenges from a matrilineal indigenous council perspective; then have an additional piece that brings these challenges in question form directly to the Traditional council in Kahnawake!
The council is to have a virtual Great Law of Peace discussion soon! So to Jenny's idea of an AMA, it is a perfect opportunity to ask these questions & others for anyone interested :)

**Comment by lrettig** [comment]
> The council is to have a virtual Great Law of Peace discussion soon! So to Jenny's idea of an AMA, it is a perfect opportunity to ask these questions & others for anyone interested :)

I love this idea more than I can express here! hehe

**Comment by HaroldDavis3** [comment]
**Blockchain Governance & Indigenous Protocols Series**

This two part series aims to give a glimpse into what makes the Blockstack ecosystem unique while also giving an update the work being done in the Blockstack newly formed independent Stacks foundation. 

The first part of this series will be looking at important points made by Lane Rettig [bold text] of the working group regarding current challenges of blockchain governance. We will focus on these challenges through the unique lense of my personal experiences & research while sitting in traditional councils of Kahnawake territory in Canada.

The second part of this series will consist of these same challenges posed by Lane put into question form, for direct answers from said traditional council in an online Q&A! Answers will be compiled here to complete this series of updates!    

**Governance of cryptographic networks faces many of the same challenges as “off-chain” governance of things like corporations and political polities. There is therefore no reason to “reinvent the wheel,” and most governance best practices apply equally to the “off-chain” and “on-chain” world. Having said that, we must also understand that cryptographic networks do operate under a novel set of restrictions, meaning that governance of such networks faces novel challenges.** 

**Permissionless participation, identity, and plutocracy**

**A common requirement of cryptographic networks is that participation in the network be permissionless, in the sense that anyone is free to transact on the network, deploy and interact with applications, validate transactions and earn rewards, etc. This is a desirable property, but in practice it leads to the challenge of Sybil resistance: how to map on-chain identities (such as IDs or wallet addresses) to off-chain identities (such as individuals and companies). 
This is especially problematic since, with no robust notion of unique identity, we cannot build naive democratic institutions such as voting, since a user could simply create many identities to amplify their voting power. It also means that we cannot, for instance, impose term limits on on-chain identities for the same reason: the real-world actor behind that identity can just create more identities to circumvent the limit. For these reasons, any meaningful notion of on-chain democracy is impossible.
What’s more, any attempt to introduce proof of work to validate identities simply reduces to plutocracy: those with access to more resources can use those resources to amplify their voting power. What we really want is a Sybil resistant “proof of unique human” algorithm. While teams including Democracy Earth continue to pursue this goal, it remains a fundamental, unsolved problem in governance of cryptoeconomic networks. For the purposes of this proposal, we assume this problem is unsolved.** 


- Perception of Corruption concept of Matrilineal Process
- ON/Off Combinations = ON-Chain Consensus > Voting for Unique human resolution
- [Limits of Blockchain thus far] Including Voices of humans & non humans in blockchain based systems —conventional governance [electoral college] 
- Importance of bottom up approaches to blockchain based systems. De Filippi Quote.


This first point from Lane gives us an opportunity to learn an important concept from the Traditional council of the Five Nations Confederacy in Kahnawake, Canada. The matrilineal council protocols are to avoid even a perception of corruption to exist. Of course this is a very short glimpse into a very complex means to peaceful confederation of these nations sustained for over two thousand years! But this concept will serve as a key motif throughout this first part. 

The perception of corruption concept already becomes relevant here in Lane’s first point. Imperative to upholding said perceptions in native council protocols is consensus decision making. The distinction of majority voting & 100% consensus being a huge protection for collective decision making in long term dynamics. In the Mohawk traditional cosmology, the matrilineal bloodline traces through the women, to our mother Earth, then our grandmother Moon, all the way to the great spiral of creation herself Sky Woman. An in depth history is kept about what is considered a familial history of all of these levels. Overall, this familial framing enables complex abstract formulas for interdisciplinary problem solving through their cosmology. But it also enables the women council’s 100% consensus to function as long term protections of voices of all of these levels, humans & nonhumans [ecologies] alike. The women representing this bloodline are thus deemed the true managers of the land & people. 

So to Lane’s point about the similarities of challenges off chain governance to on-chain; we should note the early blockchain space is guilty of not living up to avoiding a perception of corruption concept. But off chain governance in the form of conventional governance structures all the way up to international scales has a much longer history of being guilty of this as well; with the addition of drastic impacts on the planet & everyday people. As blockchain begins to impact more lives via global trade or internet architectures it will no longer have the justification of an early technological space. It can find itself falling into dangerous basins of attraction towards concentrations of wealth & power. This threatens to defeat the purpose of distributed systems efforts thus far.  After citing indigenous organization as possible research space for blockchain governance, blockchain expert Primavera De Filippi explains: 

> _“The problem to me is basically..We have few models of governance in our minds..Its a paradox because if the goal is decentralization, infrastructure is distributed, but power is not..w/out proper governance will lead to a super concentration of power..so a narrative of decentralization w/out coming with a proper governance infrastructure will never work..the problem is, we have never been acquainted with distributed systems that are not market systems..markets statically are decentralized but dynamically we don’t have one market with distributed power w/out a gov’t institution enforcing competition..we’re left with nothing, we don’t know..Blockchain is an opportunity to explore & experiment.. how do we get a fresh mind w/out being indoctrinated by everything we know today when building alternatives?.. ”_ 

> 

It is interesting to point out De Filippi’s point of the short-comings of conventional governance approaches; accurately or honestly representing voices isn’t necessarily a feature offered by such top-down structures in long term dynamics. Hence the powerful opportunity proper dialogue with the original people of the hemisphere can bring to the world of blockchain; such dialogue offers authentic alternatives to conventional governance via exposure to indigenous bottom up, commons based social organization models & decision making protocols. Proof of unique humans  via consensus as a hybrid of both on/off-chain may at first glance seem like a purpose defeating compromise of permissionless decision making; but this may be overlooking significant advantages a hybrid approach can offer in way of bottom up governance i.e blockchain based certifications of 100% consensus for on-chain decision making.  

**De facto technocracy**

**Blockchains are extraordinarily complex systems, and they are complex in multiple ways: technically, yes, but also socially, economically, etc. Effectively governing a blockchain requires the input of experts, and the dedication of a lot of time and focus. Most network stakeholders simply do not have the time or expertise to dedicate to professional governance, which means that there is constant tension between falling back on technocracy, on the one hand, and the challenge of instituting more inclusive forms of government, on the other.**


- Clans & Functions in council. 
- Council fires = Interaction & Dialogue. 
- Clan Variations & Council fire Variations = Technocracy resolutions via accurate voice representation from Varying autonomous council fires.

Again, yet another of many mechanisms important to upholding this perception of corruption concept in native decision making processes is their clan system. To Lane’s critical points about limits of expertise or other resource means resulting in fewer voices in decision making; the functions of these clans in decision making involve delegation of many layers of collective expertise or resources. Collective being the key word here. Clan titleholders are tasked with accurate representation of voices on all levels through aggregating decisions of council fires or open dialogue & interaction based consensus.  
The (Mohawk) nation has a three clan system, _Turtle, Wolf & Bear_. Others in the Five Nations may have many more of many variations. The Mohawk & Oneida are the only with three clan system in the Five Nations, as they are the most eastern & tasked with protecting the hemisphere through diplomatic protocols used for peaceful nation to nation trade for millenia. Similar to Blockstack’s architecture of simple at the core approach to security is the logic of three clans of the Mohawk in regards to securing protocols of peaceful & sustainable social organization. Complexity in represented in layers of clan variations happening more inland (these inland territories have been susceptible nation-hood status removal, while the traditional council mentioned here is the rare exception! )Hence our access to this important dialogue & matrilineal protocols that are rare to find completely intact! 

Female & male titleholders or chiefs in traditional language of the Mohawk translates to the “best of us;” they represent the voices of those in respective clans of all nations at a central Grand Council; including those clans beyond Turtle, Wolf & Bear. Focusing on these three, Wolf clan representative Stuart Myiow often says clan functions are comparable to the distinct functionalities present in protons, neutrons, & electrons. The autonomy important to the peace protocols is key in council fires in varying territories. And further stresses a capacity to overcome the challenge Lane & Primavera point to in conventional governance structures. Accurate voice representation & complex checks & balances in protocol are necessary for such a resolution to technocracy in native organization contexts.

So, we can see different aspects of social organization, with varying resources & know how are represented at the grand council. Just like the elements that make up an atom & everything that can be built with atoms, each clan adhering to its function is extremely important to the others to achieve a proper decision on behalf of the five peaceful nations. This design emphasizes the collective with infinite cultural & protocol nuances; and encourages interaction on all levels despite distinctions of demographics. [Commons engineering is an important link here, see below for more on this] This is a whole lot of consensus from many autonomous voices, from many angles; and an authentic native nation’s resolution for avoiding their own versions technocracy for thousands of years of sustained peace. We can only learn to achieve this complex resolution through proper legal dialogue via the Two Row Wampum Peace Treaty. A (pre)columbian treaty extrapolated from native cosmology, originally used between indigenous nations for millennia before being signed by Dutch, French, English, American colonists. 



**No governance equals stagnation and Tyranny of structurelessness**

**Some blockchains, such as Bitcoin, are designed to have “no governance.” In practice, of course, there is no such thing as “no governance,” so what this really means is a lack of explicit, participatory governance. Decisions are usually made by a small group of insider technocrats, a form of the tyranny of structurelessness. What’s more, such a system of government tends towards stagnation and ossification, as changes happy only very infrequently, which means the protocol may fail to keep up with the pace of technology or the needs of its users: witness the Bitcoin scaling debate.**


- Management > Governance →Stirring of Ashes
- Council process Opinion vs. Law→(De)horning= Fundamental protection for collective consensus decision making[commons]
- Tied to innovation→Preindustrial revolution

So this is an idea we can safely say is consistent with traditional native thoughts on the issue of structurelessness. It also presents an opportunity to make a distinction between governance = control; and **management** = a mothers love in managing child rearing. A good example of this is a Ceremony called The Stirring of the Ashes. Ceremony, song & dance, symbolism & other cultural details are all inextricable from the decision making protocols. 
This particular ceremony comes annually via calculating moon cycles and solstices. It represents bringing in a new cycle. Important to one’s ability to get up & stir the ashes to bring in the new cycle along with the collective in ceremony; is to have all interactions on all levels [from interpersonal relations to proper ecosystem management] resolved before the new cycle begins with this ceremony. If not, your mother has to get up & stir the ashes on your behalf; signaling to the collective the individual’s current status as it relates to his/her management by their mother. Goal being, the same isn’t true for the next cycle. 

An important lesson of the dangers of entering a new cycle with unresolved issues, thus compounding threats to social organization. Crucial here is to realize that along with a general check & balance for any general false acquisition of public status; titleholders have a three tiered eligibility criteria when chosen by female titleholders. 1) Must have a clan (native matrilineal bloodline) 2) Must have thick skin (Composure in confrontation) 3) Must be able to manage his/her own affairs. This third requirement shows how this ceremony embodies one of many mechanisms in place to track the long term morphology of micro-dynamics (most influential voices) to the nation scale. It also embodies the terminology distinctions in the results of management vs governance. 

The constitution of the Five Nations “The Great Law of Peace” was first established in the Mohawk nation. Everything is decided by discerning whether something is a matter of personal opinion with no evidence in law _the bad mind_; or if evidence can be provided,  the decision is of the _good mind_.  If consensus protocols point to titleholders falling short of the good mind; Female titleholders reserve the right to (de)horn the inadequate representative. This serves as a fundamental protection for collective based consensus decision making. 

Another critical mechanism for this protection is the commons. Far from structurelessness, engineering commons into their social organization is a powerful tool in the way of eliminating individual uncertainty while reinforcing the importance of the collective. The commons is also an engineering marvel that sets a solid foundation for sustainable innovation. The regenerative potential unlocked by open source commons is self similar to the regenerative fecundity managed by these indigenous modes of production & organization models. 

Corn is important to the commons via the regenerative relationship between soil & the _Three Sisters Corn, Beans, & Squash_. This regeneration w/agroecology design for specific genetic expressions, fractals out over millennia interacting with surrounding species giving us entire food groups: corn, squash, beans, peanuts, peppers, melons, pineapple, avocado, blueberries, strawberries, tobacco, vanilla, cocoa etc. Not to mention landscape scale modification across varying geographies. This scale of innovation may represent an interesting phenomenon of a virtually unacknowledged technological revolution, that arguably has a net positive impact far above the industrial revolution. 
Considering this is all pre-industrial innovation that avoided intensive extraction & pollution while providing a whole lot of world shifting technology. All this to emphasize evidence of the logic behind the strong native preference for explicit design[for the good mind] in organization approaches. Also an important lesson for obligations of those working in web 3.0; how the commons brought from the macro of open source licenses into the micro of open business models can unlock self organizing innovation potential via decoupling control of respective shared resources. 

**Szabo’s Law**

**A lack of explicit governance is attractive to many blockchain vanguards since, to them, a blockchain should be “extra-legal,” i.e., beyond the reach of the laws of any jurisdiction, and “not something you can reason with.” However, this presents enormous challenges from a social-legal perspective, as such systems are, in fact, probably illegal and antisocial.**


- Two Row Wampum Dialogue & legal jurisdiction of hemisphere 
- Socioeconomic alternatives opportunity needed by Blockchain based systems [De Filippi]. 

Juliet M. Oberding & Terje Norderhaug of the Blockstack community have done important pioneering work in this area of jurisdiction. And their important message of an opportunity to decentralize during an early internet can be revitalized in web 3.0. Primavera’s work leads us to more optimism on this idea. And the nation-hood status available through Two Row Wampum dialogue brings even more. 

An additional entity along with Blockstack’s newly independent foundation may provide interesting paths towards Juliet & Terje’s vision of the internet’s capacity to provide a means away from conventional centralized legal constraints. This is because the unique jurisprudence provides a freedom to build outside the boundaries of conventional organization. An important key to complex systems being-- proper initial conditions significantly impacting basins of attraction of long term dynamics. This dovetails nicely with Primavera’s thoughts on indigenous approaches as possible viable authentic alternatives to blockchain based systems.


**On chain governance is also plutocracy**

**Given these challenges, and the perception of the inefficiency of networks with off-chain governance, it’s tempting to introduce on-chain governance, where token holders vote on proposals (which may be written in dry or in wet code). However, in practice, such networks also reduce to plutocracy and are liable to a small number of plutocratic “whales” swaying or dominating the vote, to buying/selling/renting of voting power, etc. We have seen examples of all of these in practice in production networks.** 


- More on combinations of management & on-chain consensus representation potential
- Title via consensus of women’s council. Campaigns are illegal!

Will take this as chance to elaborate on exciting potentials that can come from hybrid forms of off/on-chain models in an indigenous context. Unlike representatives in conventional governments; matrilineal indigenous titleholders can not campaign for election, but instead chosen by consensus of female titleholders. Here again the perception of corruption rule is applied. Given the work involved in 100% consensus in brief context described above, and to Lane’s point of technocracy; campaigning for such weighted responsibilities of the collective allows for the mere perception of corruption, so it is deemed illegal. 

As described above blockchain based certification of indigenous councils in this context also provides many more unique checks & balances that can enable the advantages that come with on-chain decision making hybrids. Advantages akin to transparency & objective ledgers of decision making are a strong mechanism in traditional native councils. Blockchain based systems can revitalize these modes of organization with digital age speed & scale in systems design. Such scale even if just small networks of local & regional trade can help bring the physical world into digital age speed. Native guidance w/an opportunity for a corrected relationship to the hemisphere is important to the initial conditions of this next iteration of blockchain based world trade not becoming digital speed extraction of human & non-human voices.

**Preventing entrenchment**

**Without careful thought and design, the natural direction that any system of government heads is ossification: the current set of arbiters remain in power indefinitely, or hand power only to cronies or to their own family. Democracies deal with this problem through term limits and the entry of new voters (the young, immigrants). Without robust identity, democracy, or term limits, how do we deal with this problem, making sure that there is sufficient churn in the arbiter set, and that sufficient room is made for new entrants?**


- Hereditary tradition misconceptions & conflations. 
- More on perception of corruption motif. [warning system & eligibility]

Again, in a native context the protocols for organization are weighted toward the collective via consensus. This gives a different framing than we are familiar with in lives within conventional system structures & markets. In the native system, checks & balances have tangible mechanisms to keep titles held throughout millenia untainted. While in our conventional system, we are desensitized to representatives funding distasteful campaigns for tainted positions passed through entrenched generations, eloquently pointed out by Lane. Most of the checks & balances will go undescribed in this series, although Wolf clan rep, Myiow can elaborate more than myself. 

Final examples of the perception of corruption rule as it relates to entrenchment. 
The warning system-- like the protocols as a whole are extrapolations of the Mohawk Creation Story & Turtle, Wolf, & Bear. Warnings across clans, female & male titleholders, results in an extensive investigation process where titleholders can lose their title after repeat offenses. Of these offenses handling affairs is always a requirement. Affairs here referencing proper interactions with human & non-human voices alike. Shortcomings are met with appropriate weighted warnings or immediate removal of title.

Other checks that embody the perception rule include the native protocols for inter clan marriage &  hereditary title holding. Hereditary in a native context is a reference to clan not blood. And instead of a mechanism of entrenchment with western monarchies or governments; it is actually a mechanism to prevent entrenchment. Example, If your mother is wolf clan then you are wolf clan. If you hold title, then you can not marry a titleholder for sake of avoiding perceptions of corruption. You can not pass title to children or anyone that would cause bad perceptions etc. 


**Stay tuned for Part 2!**

**Comment by Topper88** [comment]
_in progress_ (gotta post unfinished for now, but be back to it shortly) 

> * What comes after the governance proposal?
Revision of the proposal by board and by community,

> * How will it be enforced?
it is the fundamentally down to the gov. protocol to make "bad-acts" economically irrational and also to drive required activities by incentive is a sustainable manner. In other words, dealing with badacts post-impact is already a fail, but those are going to be definitely golden inferences in automatic sanctions and such.
 
> * Are there any stakeholder perspectives that we're missing?
Locking a threshold sum of STX is a risk taken. The reward for locked funds is the persistence of the network and the proof of staker's devotion...full stop.
Either locked funds are utilised like active capital in economy so earned interest is justified or if is not gonna fund activity, then staker acts as a reward distributor in a managed (by gov.prot) keeping only a portion of BTC (semi-centralizied? _the structured organisation of our current system is the legacy, in itself, one of humanities greatest achievement and that is to be reiterated with blockchain_ 
a time interval of "locked" funds is useful in conditions where the governing protocol

> * How can we improve on the work that we're currently doing?
> * What can the broader Blockstack community do to ensure that we are "doing governance right"?
> * What are we hoping to take from other crypto projects and what are we hoping to avoid?
> * What is unique about the Blockstack ecosystem?
> * How do these unique qualities impact the way that we approach governance?
> * Is our approach to governance different because of these unique qualities?
> 
> **All answers will contribute to a longer form blog detailing the work that this group has done on governance so far. (Pending review and approval from group members, of course.)**

**Comment by lrettig** [comment]
@blockstackers thanks for this excellent, well thought out list of questions :)

- What comes after the governance proposal?

Hopefully, more iterations of feedback from various community members, improvement of the proposal, ongoing dialog with stakeholders (e.g., the newly-formed Stacks Foundation) about what's possible over what timeframe, etc.

After that, "ratification" of some form, whether implicit or explicit. "Implicit" could mean just transitioning, with the support of the community and in particular the governance working group, into a "Phase II" of the governance initiative where certain concrete things, such as the SIP process, work according to the practices and principles laid out in the proposal. It could mean rough consensus on something like a code of conduct, etc. A more "explicit" ratification process could involve drawing up a list of stakeholders and holding some sort of a vote - and/or voting by miners. I like the idea of tying ratification of the proposal/foundational documents to the ratification and launch of Stacks 2.0 on the part of the miners.

- How will it be enforced?

This is a tricky question with a fairly complex answer :) In brief, social norms - to the extent that all or most of us are onboard with certain foundational principles, things like shared values, governance principles, a code of conduct, etc. I think enforcement will happen at the social layer and will take care of itself. Looking slightly longer-term, I think we need to consider a system of checks and balances and somewhat more explicit enforcement of certain aspects of governance, along the lines of granting funding to proposals that have been approved (and denying it to those that have not), veto power over certain decisions, etc. - a lot of these ideas are already laid out in the governance proposal.

- Are there any stakeholder perspectives that we're missing?

I worry about the class of "users," i.e., current and future users of apps built on the stacks ecosystem that are not active in governance today.

- How can we improve on the work that we're currently doing?

I think we could do a better job of communicating the things we're discovering, learning, and planning together to those who are less active in the governance working group - this blog post is a great start!

- What can the broader Blockstack community do to ensure that we are "doing governance right"?

I think there should be some KPIs that we are held accountable for. In governance, these are not always immediately obvious and require some thought and discussion, but some ideas include degree of participation in various forums/channels, "net promoter score"-style satisfaction scores, and overall sentiment. In governance, it's sometimes the case that "no news is good news" (e.g., everyone is happy with things the way they are so they have nothing to add), which is by definition hard to measure :)

I think the most important thing the community can do is speak up and make their voices heard, especially if they disagree with something.

- What are we hoping to take from other crypto projects and what are we hoping to avoid?

We are hoping to take the things that work well - and I think we've done a good job of that, using things like GitHub for project management, regular, recorded calls, borrowing a lot of ideas from Zcash wrt setting up and operating the Foundation, etc. In my mind we are hoping to avoid unaccountable, informal governance in the hands of a small number of well-connected elites, i.e, tyranny of structurelessness.

- What is unique about the Blockstack ecosystem?

A strong focus on a shared set of values and principles, e.g., "can't be evil," "user-owned Internet," etc. Also, a belief in Bitcoin as an "anchor" for security. A bit more of a focus on applications and less on other uses of blockchain networks (e.g., tokens, private communications).

- How do these unique qualities impact the way that we approach governance?

Having a concrete set of shared values is absolutely essential and is the starting point for everything else that we do in governance! We should think and discuss more how these values have manifest in the work we've done to date, and how we make sure they're reflected in the work we do going forward. As one concrete example, if we are committed to building a "user-owned Internet," how do we make sure that governance respects the needs of the "user" - who may not be present in these conversations today?

- Is our approach to governance different because of these unique qualities?

I hope so! :)

**Comment by HaroldDavis3** [comment]
**- What are we hoping to take from other crypto projects and what are we hoping to avoid?**

We are looking towards innovative models of inclusive decision making that can be found in structures in Zcash. We are also looking to address fundamental questions in the blockchain governance space: How to ensure distributed power [social] in long term dynamics of distributed systems [infrastructure]; Future Ecological protections etc.

**- What is unique about the Blockstack ecosystem?**

The PBC engineering team has really built something special with the new PoX consensus algorithm. It can enable a co-op like structure in the space like never seen before in the world of finance. It also brings an unprecedented access to space via novel means to deploying new chains! All this Innovation lends itself beautifully to further structure building atop this infrastructure; structures that have the opportunity to be truly orthogonal to modern socioeconomics.
   
**- How do these unique qualities impact the way that we approach governance?**

Well here is a recent insight from Jude of the engineering team!: 
> " I think that the fact that Stacks 2.0 has app chains changes the responsibilities of the steering committee somewhat from the equivalent bodies in other projects. In particular, the SC can almost always afford to say "no" to a SIP, since the SIP's proposer is free to start up an app chain that implements the SIP and run it indefinitely. In fact, if someone wanted to have a blockchain with feature X, where X is not implemented today, they could just skip right to deploying an app chain with X enabled and not even bother to send a SIP! I think this sort of behavior ought to be encouraged -- i.e. the recommended course of action for someone who wants feature X would be to first build and deploy an app chain, and then maybe later send in a SIP to get X incorporated into the Stacks chain codebase." 

**- Is our approach to governance different because of these unique qualities?**

Jude's insights above show Blockstack's governance approach to have a unique capacity to leverage work done in R+D at the protocol level, to design innovation into the decision making process in itself! Proposals can be tested via chain deployment success or failure. Building in a potent mechanism to explore chain models & viable approaches to chain self sufficiency in the broader ecosystem.
