### ISSUE TITLE
Community Board Seat

### ISSUE THREAD

**Issue by whoabuddy** [stacksgov/pm#66]
Placeholder issue for discussion of community board seat, per @blocks8 on call 17 #61.

**Comment by whoabuddy** [comment]
@blocks8 mentioned this topic in Discord on 7/15/2020:

> This one needs work. Are there members here who want to be part of a committee to collect info & research on the best way to execute?

**Comment by blocks8** [comment]
Sharing an update: https://forum.stacks.org/t/building-a-community-board-seat-community-leadership-requested/11412

**Comment by SeanMGonzalez** [comment]
I have been working with Ryan, Dan, and others from Blockstack on this Community Board Seat challenge. I also recently discovered a prototype Dapp called Liquid Democracy (https://bit.ly/2VVCveY), which happens to reflect the contract structures I've been developing for years to give tech consultants more power during and after their gigs (https://www.meetup.com/ACM-DC/events/274794629/). 
I believe Blockstack, its community, and Dapps, have created an opportunity for a new kind of representation, one where the community can act dynamically on new information, new relationships, new experiences, and new knowledge. 
I see a world where consensus is objectively verified and summarily represented by a community volunteer. 
I see new information pushed to verified community members, where they can allow their default vote or cast new votes.
I see new relationships and experiences changing peoples' perspective, which may compel them to update their vote.
I see people delegating their votes for different topics to members whose expertise they trust.
I see knowledge driving decisions.

**Comment by jennymith** [comment]
@ryanarndtcm Mind sharing an update on this issue as well? Thank you!

**Comment by blocks8** [comment]
Thanks for the feedback @SeanMGonzalez! 

The next steps are in the hands of the community. It'd be great to see a proposal, or a grant application to do the research to create the proposal, for the community board seat. We've given the green light for the community to have a community board seat, but it's up to the community to determine how to fill that role, how it will be managed over time, and who will be sent on behalf of the community. This may be a bit of an experiment in true community ownership, so the foundation is here to be supportive, but will be mostly hands off in terms of the who and how to make sure it is community owned - as envisioned.

**Comment by SeanMGonzalez** [comment]
> Thanks for the feedback @SeanMGonzalez!
> 
> The next steps are in the hands of the community. It'd be great to see a proposal, or a grant application to do the research to create the proposal, for the community board seat. ...

WOW, one more reason to support this community! 

I've started the process on grants.stacks.org , looking forward to getting feedback :)

**Comment by PeterSchurman** [comment]
I love the Liquid Democracy idea. Sounds like it might take some time to implement.

In the meantime, one simple, out-of-the-box option to enable collaborative deliberation and decision-making, slightly more robust than GitHub for these functions, is https://www.loomio.org/

**Comment by SeanMGonzalez** [comment]
> I love the Liquid Democracy idea. Sounds like it might take some time to implement.
> 
> In the meantime, one simple, out-of-the-box option to enable collaborative deliberation and decision-making, slightly more robust than GitHub for these functions, is https://www.loomio.org/

Great demo, useful tool! Looks like we'll need the Enterprise version, would you happen to know how much that is? https://www.loomio.org/pricing

**Comment by PeterSchurman** [comment]
I don't know their pricing but I do know some folks there.

**Comment by ryanarndtcm** [comment]
"what sort of things are needed for a community board member? is there an assessment of some sort we could share publicly?"

From @blocks8 "based on info from our first board nominations post : https://forum.stacks.org/t/call-for-stacks-foundation-board-nominations/10853

The foundation was built by the community, for the community. The Community board representative would serve as the voice of the community in board meetings. The exact requirements can be decided by the community in the Community Board Seat proposal. 

Overall, we think individuals who can bring expertise in one or more of following areas would be ideal: 

- Open source software development
- Blockchain development
- Foundation or nonprofit experience in the areas of data, privacy, and digital rights
- Crypto and token economics
- Governance mechanisms and architecture
- Community development and public policy "

**Comment by SeanMGonzalez** [comment]
@ryanarndtcm perhaps the board would be interested in Community Advisors. With a curated list of community members' expertise, the board could ask questions, get community feedback, and source volunteers. Then the Community Board Seat would be about asking questions of the community and generating reports from their answers.

**Comment by dantrevino** [comment]
@SeanMGonzalez the idea is to represent the community in Stacks Foundation decisions.  That person and their decisions should be accessible. And we need a mechanism to fill/adjust the person in that seat.

**Comment by joberding** [comment]
Let's not forget that there are both regular board seats and a community board seat. It has been my long held position since the beginning of the Governance Group that a member of the community should be on the board as an official board member with voting power to contribute to the decision making of the board on behalf of the community. 

From my research, most decentralized communities have at least one community member and usually two on the board who have been elected by the community and have voting power regarding decisions by the board. As I recall, a good example is ZCash. While the community board seat is a rotating position changing out the community member for each board meeting that provides a community voice with no voting power. This definition is based on my recollection of our discussions on the Governance group since February 2019. 

@SeanMGonzalez While I find the concept of liquid democracy interesting (and will address more on this in a separate post) , I believe our first step should be to define the roles of the two types of board members with input from the Stacks Foundation, Governance group and the community. I'm happy to contribute to this work.

Would be interested in feedback from @dantrevino @blocks8 regarding the two types of board seats as set forth above.

**Comment by SeanMGonzalez** [comment]
Yes, I agree @joberding . The board has identified the types of expertise they'd like in a community board member:

- Open source software development
- Blockchain development
- Foundation or nonprofit experience in the areas of data, privacy, and digital rights
- Crypto and token economics
- Governance mechanisms and architecture
- Community development and public policy

"Unicorn" is one way to describe someone with all those capabilities, so having two seats instead of one makes sense. That said, it's been hard enough finding one person and the board would have to vote to create a second seat, so two may be down the road. Part of the reason finding a good candidate has been challenging is the community structure is still being defined. It would also be very helpful to have the responsibilities and expectations of the board seat more specifically spelled out, as @joberding mentioned.

We have an opportunity to define a community engagement strategy that leverages the forward thinking of this board, this community, and web3 capabilities. This is a big challenge, it could easily take all 2021 to define well. I believe the first Community Board seat will need to focus on defining the role for the future.

**Comment by joberding** [comment]
@SeanMGonzalez I am not sure that they expect all of that expertise in one person because that indeed would be a unicorn. :) 

A number of people were nominated by the community, some were community members like myself and some were famous blockchain/crypto personalities. However, the full list of who was nominated by the community was never shared with the community in a transparent fashion. 

I don't think there is a problem finding people who are interested in a community board member or voting board member position or who fall within the areas of expertise but the real problem lies in creating the process of selecting the person or persons and having the foundation accept the result of the process.  

From a legal perspective, I also don't think there is any great issue in adding a new board member with voting rights (or two) along with having community observers. It only takes the political will of the board to make it happen which since there are no community observers to report on the desires and will of community and no tested method to accurately surface the will leaves us in a blocked situation.

Here's a solution: get observers to sit in on the board meetings asap and be the voice of the community. We can decide the roles as we go. I suggest at least two observers rotating the role for each board meeting. While I have been nominated and desire to be a voting board member, I am happy to serve as an observer until such time as there is a call for a community board member with voting rights.

**Comment by SeanMGonzalez** [comment]
@joberding yes, observers on the board is the next step. We were discussing this today in the StacksGov and StacksEcosystem calls, the next board meeting is February 5th and I'm planning to have a proposal ready to present. You and I are apparently sharing some conclusions: that we can decide the roles as we go, the stacks community has great expertise we can engage, and there is no tested method to accurately surface the will of the community.

I'd like to write a proposal for how a couple of board members/observers could address these challenges over the next year. Would you like to write it with me?

**Comment by joberding** [comment]
I jumped on the StacksGov call as you were presenting so did not hear the complete presentation.  I agree that we have some shared conclusions and look forward to writing the proposal with you.

**Comment by joberding** [comment]
Noting this issue relevant to current discussion for historical purposes: https://github.com/stacksgov/pm/issues/17

**Comment by SeanMGonzalez** [comment]
The Stacks Board meeting is this Friday, we're hoping to have good results from our BlockSurvey and officially get the Community Board position started. Thanks in advance for your feedback :)
https://shrl.ink/5tYn

**Comment by whoabuddy** [comment]
I want to signal my support for this, thank you for the hard work!

**Comment by BaiHuLaoShi** [comment]
Per today's Governance meet, I agree to Sean and Juliet trading off the first two quarterly slots for community observers.

My understanding is that Sean and Juliet will develop SOPs and expectations for bi-directional board communication with the Stacks community through the board observer role, allowing for willing community members to more easily slot into the role moving forward.

**Comment by HaroldDavis3** [comment]
> I want to signal my support for this, thank you for the hard work!

Doing the same of course! 💯

**Comment by joberding** [comment]
@dantrevino @jennymith Can you show your support for Sean and I as community observers

**Comment by dantrevino** [comment]
Yes I'm absolutely on board with this idea. Both have demonstrated a commitment to bringing a community voice to foundation business.

**Comment by jennymith** [comment]
It's gonna be a "yay" for me :).

**Comment by whoabuddy** [comment]
From #139:

- looking forward to town hall tomorrow, format inspired by meetings/thoughts here
- debates and details around community board seat and voting implications
  - @SeanMGonzalez and @joberding researching for long-term
  - balancing community need for representation and actual board operations

**Comment by whoabuddy** [comment]
Closing out after discussion in #167 that the community board seat is active.

**Comment by RagnarLifthrasir** [comment]
Please see https://github.com/stacksgov/Stacks-Grant-Launchpad/issues/665
